version: 2 
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.13.5 
    
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps: 
      - checkout 
      - run:
          name: BUILD
          command: go get -d -v ./... && go build -v ./...
      - run:
          name: TEST
          command: go test -v ./...
workflows:
  version: 2
  build-workflow:
    jobs:
      - build