version: 2 
jobs: 
  build-go1.13.5: 
    docker: 
      - image: circleci/golang:1.13.5 
    
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps: 
      - checkout 
      - run: go test -v -race ./ ...
      - run: go test -v -race cmd/{{REPO_NAME}}/tlv.go
workflows:
  version: 2
  build_and_test:
  jobs:
    - build-go1.13.5